# Generated by Django 4.0.5 on 2022-07-21 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
