# Generated by Django 4.0.5 on 2022-07-21 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('valid_from', models.DateTimeField(default=datetime.date.today)),
                ('valid_to', models.DateTimeField(default=datetime.date.today)),
                ('discount_price', models.IntegerField(default=100)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
