# Generated by Django 4.0.5 on 2022-07-21 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
